modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Mrbysco/SoundMimicry/issues"
license="MIT"

[[mods]]
modId="soundmimicry"
version="${file.jarVersion}"
displayName="Sound Mimicry"
displayURL="https://www.curseforge.com/minecraft/mc-mods/sound-mimicry"
authors="Mrbysco, ShyNieke"
credits="ShyNieke for the idea"
description='''
Adds a block that can emmit sounds
'''

[[dependencies.soundmimicry]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"
[[dependencies.soundmimicry]]
modId="neoforge"
type="required"
versionRange="[21.1.1,)"
ordering="NONE"
side="BOTH"
[[mixins]]
config="soundmimicry.mixins.json"